[workspace]
members = ["crates/alef-core", "crates/alef-modules", "crates/alef-runtime", "crates/alef"]
exclude = ["patches/winit"]
resolver = "2"

[profile.dev]
debug = 0

[patch.crates-io]
servo-paint = { path = "patches/servo-paint" }
servo-paint-api = { path = "patches/servo-paint-api" }
winit = { path = "patches/winit" }
surfman = { path = "patches/surfman" }
