// Generated by scripts/gen-types.mjs from the Rust DTOs. Do not edit.
export type AlefError = { code: ErrorCode, message: string, details?: unknown, };

/**
 * Options of `dialog.confirm`.
 */
export type ConfirmOptions = {
  /**
   * Title of the dialog.
   */
  title?: string,
  /**
   * The question.
   */
  message: string,
  /**
   * Text of the confirming button. Without both labels the buttons are the system's; with one,
   * the other reads `OK` or `Cancel`.
   */
  okLabel?: string,
  /**
   * Text of the declining button.
   */
  cancelLabel?: string, };

/**
 * What the user gives for a right.
 */
export type Decision = "allow" | "substitute" | "deny";

export type ErrorCode = "NOT_FOUND" | "ALREADY_EXISTS" | "NOT_A_DIRECTORY" | "IS_A_DIRECTORY" | "DIRECTORY_NOT_EMPTY" | "PERMISSION_DENIED" | "INVALID_ARGUMENT" | "TIMEOUT" | "CLOSED" | "BUSY" | "NETWORK" | "NOT_AVAILABLE" | "MANIFEST_INVALID" | "INTERNAL";

/**
 * A named group of file extensions of a file dialog.
 */
export type FileFilter = {
  /**
   * Text the dialog shows for the group.
   */
  name: string,
  /**
   * Extensions without the dot (`png`); `*` stands for every file.
   */
  extensions: Array<string>, };

/**
 * The weight a message dialog gives its text.
 */
export type MessageKind = "info" | "warning" | "error";

/**
 * Options of `dialog.message`.
 */
export type MessageOptions = {
  /**
   * Title of the dialog.
   */
  title?: string,
  /**
   * The text.
   */
  message: string,
  /**
   * Default `info`.
   */
  kind?: MessageKind, };

/**
 * A display. Logical pixels are physical ones divided by the scale factor of this display, so the
 * rectangles of displays with different scale factors do not tile exactly.
 */
export type MonitorInfo = {
  /**
   * Name reported by the system, when there is one.
   */
  name: string | null,
  /**
   * The whole display.
   */
  bounds: Rect,
  /**
   * The part of the display that is not taken by the task bar, Dock or panels.
   */
  workArea: Rect, scaleFactor: number, primary: boolean, };

/**
 * Options of `dialog.open`.
 */
export type OpenOptions = {
  /**
   * Title of the dialog.
   */
  title?: string,
  /**
   * File groups; not for a folder dialog.
   */
  filters?: Array<FileFilter>,
  /**
   * Several choices at once; default `false`.
   */
  multiple?: boolean,
  /**
   * Choose folders instead of files; default `false`.
   */
  directory?: boolean,
  /**
   * Folder the dialog starts in, or a file whose folder and name it starts with; absolute.
   */
  defaultPath?: string, };

/**
 * A point in logical pixels.
 */
export type Point = { x: number, y: number, };

/**
 * A rectangle in logical pixels.
 */
export type Rect = { x: number, y: number, width: number, height: number, };

/**
 * Edge or corner a drag-resize starts from.
 */
export type ResizeEdge = "north" | "northEast" | "east" | "southEast" | "south" | "southWest" | "west" | "northWest";

/**
 * A resource (file, socket, database, process...) owned by a session.
 */
export type ResourceId = number;

/**
 * One thing the manifest asks for, as the consent window shows it and the store remembers it:
 * the name of the permission and, where it has scopes, one scope as the manifest wrote it.
 */
export type Right = {
  /**
   * `fs.read`, `net.http`, `app.env`, `clipboard.read`, ...
   */
  permission: string,
  /**
   * The scope entry (`$DOCUMENTS/**`, `https://example.com/*`, an environment variable name);
   * `None` for a right without scopes (`clipboard.read`, `secrets`).
   */
  scope?: string, };

/**
 * Options of `dialog.save`.
 */
export type SaveOptions = {
  /**
   * Title of the dialog.
   */
  title?: string,
  /**
   * File groups.
   */
  filters?: Array<FileFilter>,
  /**
   * Folder the dialog starts in, or a file whose folder and name it starts with; absolute.
   */
  defaultPath?: string, };

/**
 * A document session: one window plus one page load.
 */
export type SessionId = number;

/**
 * A transport stream between the page and the runtime.
 */
export type StreamId = number;

/**
 * The colour scheme of the desktop.
 */
export type Theme = "light" | "dark";

/**
 * State of a window (`window.state`, event `runtime.window.state`). Sizes and positions are
 * logical pixels: the inner size and the position of the outer frame.
 */
export type WindowInfo = { label: string,
  /**
   * Grows with every change, so a stale snapshot can be told from a newer one.
   */
  revision: number, title: string, width: number, height: number, x: number | null, y: number | null, scaleFactor: number, focused: boolean, maximized: boolean,
  /**
   * `None` when the platform cannot tell.
   */
  minimized: boolean | null,
  /**
   * `None` when the platform cannot tell.
   */
  visible: boolean | null, decorated: boolean, resizable: boolean, fullscreen: boolean, alwaysOnTop: boolean,
  /**
   * Page zoom of the document (1 = 100 %).
   */
  zoom: number, supportsDragResize: boolean, };
