// Generated by scripts/gen-types.mjs from alef-core. Do not edit.
export type AlefError = { code: ErrorCode, message: string, details?: unknown, };

export type ErrorCode = "NOT_FOUND" | "ALREADY_EXISTS" | "PERMISSION_DENIED" | "INVALID_ARGUMENT" | "TIMEOUT" | "CLOSED" | "BUSY" | "NOT_AVAILABLE" | "MANIFEST_INVALID" | "INTERNAL";

/**
 * A resource (file, socket, database, process...) owned by a session.
 */
export type ResourceId = number;

/**
 * A document session: one window plus one page load.
 */
export type SessionId = number;

/**
 * A transport stream between the page and the runtime.
 */
export type StreamId = number;
