// Generated by scripts/gen-types.mjs from the Rust DTOs. Do not edit.
/**
 * Application environment permissions.
 */
export type AppPermissions = {
  /**
   * Exposed environment variables.
   */
  env: Array<string>, };

/**
 * Value type of a command-line option.
 */
export type ArgKind = "string" | "number" | "boolean";

/**
 * A declared option: `--name <value>`, `--name=<value>` or `-s <value>`.
 */
export type ArgOption = {
  /**
   * Long name: lowercase letters, digits and hyphens; `help` and `version` are generated.
   */
  name: string,
  /**
   * One-character short name.
   */
  short?: string,
  /**
   * Value type.
   */
  type: ArgKind,
  /**
   * Text of the generated `--help`.
   */
  description?: string, };

/**
 * Where the arguments that are not options go.
 */
export type ArgPositional = {
  /**
   * Placeholder in the generated usage line.
   */
  name: string,
  /**
   * Text of the generated `--help`.
   */
  description?: string, };

/**
 * Command-line schema of the application (`app.args()`, generated `--help`/`--version`).
 */
export type Arguments = {
  /**
   * Declared options.
   */
  options: Array<ArgOption>,
  /**
   * Positional arguments; without it a stray argument is a usage error.
   */
  positional?: ArgPositional, };

/**
 * A declared command: the program and the argument template are fixed by the manifest.
 */
export type CliCommand = {
  /**
   * Lowercase letters, digits and hyphens, not starting with a hyphen; unique in the list.
   */
  name: string,
  /**
   * A bare program name, an absolute path or `sidecar:<name>`.
   */
  program: string,
  /**
   * Arguments; an element that is exactly `{param}` is replaced by the value the page passes
   * (`param`: a lowercase letter, then letters and digits), any other element is passed as is.
   * In Ktav write brace-enclosed elements as raw items (`:: {path}`).
   */
  args: Array<string>,
  /**
   * Non-empty text shown to the user.
   */
  description: string, };

/**
 * Clipboard permissions.
 */
export type ClipboardPermissions = {
  /**
   * Whether clipboard reads are allowed.
   */
  read: boolean, };

/**
 * Command execution permissions.
 */
export type CliPermissions = {
  /**
   * Executable commands; omitted means no direct execution permission.
   */
  exec?: Array<string>,
  /**
   * Fixed commands the page may run by name; each is a right of its own (`cli.command`).
   */
  commands?: Array<CliCommand>, };

/**
 * External-resource policy; all fields are required.
 */
export type External = {
  /**
   * Allowed connections.
   */
  connect: Array<string>,
  /**
   * Resource loading policy.
   */
  load: ExternalLoad, };

/**
 * External resource lists; all fields are required.
 */
export type ExternalLoad = {
  /**
   * Allowed scripts.
   */
  scripts: Array<string>,
  /**
   * Allowed styles.
   */
  styles: Array<string>,
  /**
   * Allowed images.
   */
  images: Array<string>,
  /**
   * Allowed fonts.
   */
  fonts: Array<string>,
  /**
   * Allowed media.
   */
  media: Array<string>,
  /**
   * Allowed frames.
   */
  frames: Array<string>, };

/**
 * Filesystem permissions.
 */
export type FsPermissions = {
  /**
   * Readable filesystem paths.
   */
  read: Array<string>,
  /**
   * Writable filesystem paths.
   */
  write: Array<string>, };

/**
 * Pixels or a percentage of a screen (for example `"70%work"`). A number (px) or a string is accepted on input; serialized values are always strings.
 */
export type Length = number | string;

/**
 * Application manifest with required security policy sections.
 */
export type Manifest = {
  /**
   * Reverse-DNS-like application identifier.
   */
  id: string,
  /**
   * Display name.
   */
  name: string,
  /**
   * Non-empty version string.
   */
  version: string,
  /**
   * Declared windows; an empty list is allowed (a console utility or a service).
   */
  windows: Array<WindowDef>,
  /**
   * A console utility: no window, and the process has stdin, stdout and stderr (`app.stdin`...).
   * Needs `windows: []`.
   */
  console: boolean,
  /**
   * The entry document of an application without windows (a root-relative path, `/` when omitted).
   * Needs `windows: []`.
   */
  entry?: string,
  /**
   * External-resource policy.
   */
  external: External,
  /**
   * Permissions policy.
   */
  permissions: Permissions,
  /**
   * Command-line schema; an application without it takes no arguments.
   */
  arguments?: Arguments, };

/**
 * Window monitor selection.
 */
export type Monitor = "primary" | "cursor";

/**
 * Network permissions.
 */
export type NetPermissions = {
  /**
   * HTTP destinations.
   */
  http: Array<string>,
  /**
   * Socket destinations.
   */
  socket: Array<string>, };

/**
 * Complete permission policy. Every subsection is required except `window`.
 */
export type Permissions = {
  /**
   * Filesystem access.
   */
  fs: FsPermissions,
  /**
   * Command execution.
   */
  cli: CliPermissions,
  /**
   * Network access.
   */
  net: NetPermissions,
  /**
   * External shell access.
   */
  shell: ShellPermissions,
  /**
   * Clipboard access.
   */
  clipboard: ClipboardPermissions,
  /**
   * Global shortcuts.
   */
  shortcut: ShortcutPermissions,
  /**
   * Secret access.
   */
  secrets: boolean,
  /**
   * Application environment access.
   */
  app: AppPermissions,
  /**
   * Runtime window creation; denied when the section is absent.
   */
  window?: WindowPermissions, };

/**
 * External shell permissions.
 */
export type ShellPermissions = {
  /**
   * Allowed external URLs.
   */
  openExternal: Array<string>, };

/**
 * Global shortcut permissions.
 */
export type ShortcutPermissions = {
  /**
   * Whether global shortcuts are allowed.
   */
  global: boolean, };

/**
 * A declared application window.
 */
export type WindowDef = {
  /**
   * Stable window label.
   */
  label: string,
  /**
   * Root-relative URL.
   */
  url: string,
  /**
   * Window width.
   */
  width: Length,
  /**
   * Window height.
   */
  height: Length,
  /**
   * Optional minimum width.
   */
  minWidth?: Length,
  /**
   * Optional minimum height.
   */
  minHeight?: Length,
  /**
   * Optional maximum width.
   */
  maxWidth?: Length,
  /**
   * Optional maximum height.
   */
  maxHeight?: Length,
  /**
   * Monitor selection.
   */
  monitor: Monitor,
  /**
   * Window placement.
   */
  position: WindowPosition,
  /**
   * Restore the window.
   */
  restore: boolean,
  /**
   * Title; the application name when omitted.
   */
  title?: string,
  /**
   * Native frame with title bar and buttons; on when omitted.
   */
  decorations?: boolean,
  /**
   * Whether the user can resize the window; on when omitted.
   */
  resizable?: boolean, };

/**
 * Window permissions.
 */
export type WindowPermissions = {
  /**
   * Whether the application may open windows at runtime (`window.create`).
   */
  create: boolean, };

/**
 * The string `center` or explicit coordinates.
 */
export type WindowPosition = "center" | { x: Length, y: Length };
