// Generated by scripts/gen-types.mjs from alef-core. Do not edit.
/**
 * Application environment permissions.
 */
export type AppPermissions = {
  /**
   * Exposed environment variables.
   */
  env: Array<string>, };

/**
 * Clipboard permissions.
 */
export type ClipboardPermissions = {
  /**
   * Whether clipboard reads are allowed.
   */
  read: boolean, };

/**
 * Command execution permissions.
 */
export type CliPermissions = {
  /**
   * Executable commands.
   */
  exec: Array<string>, };

/**
 * External-resource policy; all fields are required.
 */
export type External = {
  /**
   * Allowed connections.
   */
  connect: Array<string>,
  /**
   * Resource loading policy.
   */
  load: ExternalLoad, };

/**
 * External resource lists; all fields are required.
 */
export type ExternalLoad = {
  /**
   * Allowed scripts.
   */
  scripts: Array<string>,
  /**
   * Allowed styles.
   */
  styles: Array<string>,
  /**
   * Allowed images.
   */
  images: Array<string>,
  /**
   * Allowed fonts.
   */
  fonts: Array<string>,
  /**
   * Allowed media.
   */
  media: Array<string>,
  /**
   * Allowed frames.
   */
  frames: Array<string>, };

/**
 * Filesystem permissions.
 */
export type FsPermissions = {
  /**
   * Readable filesystem paths.
   */
  read: Array<string>,
  /**
   * Writable filesystem paths.
   */
  write: Array<string>, };

/**
 * Pixels or a percentage of a screen (for example `"70%work"`). A number (px) or a string is accepted on input; serialized values are always strings.
 */
export type Length = number | string;

/**
 * Application manifest with required security policy sections.
 */
export type Manifest = {
  /**
   * Reverse-DNS-like application identifier.
   */
  id: string,
  /**
   * Display name.
   */
  name: string,
  /**
   * Non-empty version string.
   */
  version: string,
  /**
   * Declared windows; an empty list is allowed.
   */
  windows: Array<WindowDef>,
  /**
   * External-resource policy.
   */
  external: External,
  /**
   * Permissions policy.
   */
  permissions: Permissions, };

/**
 * Window monitor selection.
 */
export type Monitor = "primary" | "cursor";

/**
 * Network permissions.
 */
export type NetPermissions = {
  /**
   * HTTP destinations.
   */
  http: Array<string>,
  /**
   * Socket destinations.
   */
  socket: Array<string>, };

/**
 * Complete permission policy. Every subsection is required.
 */
export type Permissions = {
  /**
   * Filesystem access.
   */
  fs: FsPermissions,
  /**
   * Command execution.
   */
  cli: CliPermissions,
  /**
   * Network access.
   */
  net: NetPermissions,
  /**
   * External shell access.
   */
  shell: ShellPermissions,
  /**
   * Clipboard access.
   */
  clipboard: ClipboardPermissions,
  /**
   * Global shortcuts.
   */
  shortcut: ShortcutPermissions,
  /**
   * Secret access.
   */
  secrets: boolean,
  /**
   * Application environment access.
   */
  app: AppPermissions, };

/**
 * External shell permissions.
 */
export type ShellPermissions = {
  /**
   * Allowed external URLs.
   */
  openExternal: Array<string>, };

/**
 * Global shortcut permissions.
 */
export type ShortcutPermissions = {
  /**
   * Whether global shortcuts are allowed.
   */
  global: boolean, };

/**
 * A declared application window.
 */
export type WindowDef = {
  /**
   * Stable window label.
   */
  label: string,
  /**
   * Root-relative URL.
   */
  url: string,
  /**
   * Window width.
   */
  width: Length,
  /**
   * Window height.
   */
  height: Length,
  /**
   * Optional minimum width.
   */
  minWidth?: Length,
  /**
   * Optional minimum height.
   */
  minHeight?: Length,
  /**
   * Optional maximum width.
   */
  maxWidth?: Length,
  /**
   * Optional maximum height.
   */
  maxHeight?: Length,
  /**
   * Monitor selection.
   */
  monitor: Monitor,
  /**
   * Window placement.
   */
  position: WindowPosition,
  /**
   * Restore the window.
   */
  restore: boolean, };

/**
 * The string `center` or explicit coordinates.
 */
export type WindowPosition = "center" | { x: Length, y: Length };
