// Generated by scripts/gen-types.mjs from the Rust DTOs. Do not edit.
/**
 * Identity of the running application (`app.info`).
 */
export type AppInfo = { id: string, name: string, version: string,
  /**
   * Version of the Alef runtime executing the application.
   */
  runtimeVersion: string, };

/**
 * A parsed option value, typed by the schema.
 */
export type ArgValue = boolean | number | string;

/**
 * One entry of `fs.readDir`: the entry itself, a link is not followed.
 */
export type DirEntry = { name: string,
  /**
   * The path of the entry as the application names it.
   */
  path: string, kind: FileKind, size: number, };

export type FileKind = "file" | "dir" | "symlink" | "other";

/**
 * `fs.stat` and `fs.lstat`.
 */
export type FileStat = { kind: FileKind,
  /**
   * Bytes; 0 for a folder.
   */
  size: number,
  /**
   * Milliseconds since the Unix epoch; absent where the file system keeps no such time.
   */
  modified?: number, accessed?: number, created?: number, readonly: boolean, };

/**
 * Facts about the machine (`os.info`).
 */
export type OsInfo = {
  /**
   * `windows`, `macos`, `linux` or another Rust `target_os` name.
   */
  platform: string,
  /**
   * `x86_64`, `aarch64` or another Rust `target_arch` name.
   */
  arch: string,
  /**
   * OS release: `10.0.19045.6456`, `14.5`, `24.04`; `unknown` if the system does not tell.
   */
  version: string,
  /**
   * BCP 47 tag of the user's language, `und` if unknown.
   */
  locale: string, hostname: string, };

/**
 * The command line of the application.
 */
export type ParsedArgs = {
  /**
   * Every argument as given (lossy for text that is not Unicode).
   */
  raw: Array<string>,
  /**
   * Options that were given, by long name.
   */
  parsed: { [key in string]: ArgValue },
  /**
   * Arguments that are not options, in order.
   */
  positional: Array<string>, };

/**
 * One frame of the stream of `fs.watch`.
 */
export type WatchEvent = { kind: WatchKind,
  /**
   * The path as the application names it.
   */
  path: string, to?: string, };

/**
 * What happened to a path `fs.watch` watches.
 */
export type WatchKind = "create" | "modify" | "remove" | "rename" | "overflow";
