// SPDX-License-Identifier: MIT OR Apache-2.0
// node --test scripts/gen-types.test.mjs: the generator is deterministic and its check bites.
import assert from 'node:assert/strict';
import { cp, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';
import { compareDirectories, generateInto, normalize } from './gen-types.mjs';

const root = fileURLToPath(new URL('../', import.meta.url));
const committed = path.join(root, 'packages', 'api', 'types');
const scratch = path.join(root, 'backend', 'target', 'gen-types', 'test');
const FILES = ['core.ts', 'manifest.ts', 'index.ts'];

const readAll = directory => Promise.all(FILES.map(name => readFile(path.join(directory, name))));

test('two generations are byte-identical and equal to the committed files', async () => {
  const first = path.join(scratch, 'first');
  const second = path.join(scratch, 'second');
  await generateInto(first);
  await generateInto(second);
  assert.deepEqual(await readAll(second), await readAll(first));
  assert.deepEqual(await compareDirectories(first, committed), []);
  for (const buffer of await readAll(first)) {
    assert.ok(!buffer.includes(0x0d), 'LF only');
    assert.equal(buffer.at(-1), 0x0a, 'trailing newline');
  }
});

test('the check rejects a one-byte change, a missing file and a stray file', async () => {
  const copy = path.join(scratch, 'mutated');
  await rm(copy, { recursive: true, force: true });
  await cp(committed, copy, { recursive: true });
  assert.deepEqual(await compareDirectories(committed, copy), []);

  const file = path.join(copy, 'core.ts');
  const original = await readFile(file, 'utf8');
  const line = original.split('\n').findIndex(text => text.includes('number')) + 1;
  await writeFile(file, original.replace('number', 'bigint'));
  assert.deepEqual(await compareDirectories(committed, copy), [`core.ts: differs at line ${line}`]);

  await writeFile(file, original);
  await rm(path.join(copy, 'manifest.ts'));
  assert.deepEqual(await compareDirectories(committed, copy), ['manifest.ts: missing']);

  await writeFile(path.join(copy, 'extra.ts'), 'export {};\n');
  assert.deepEqual(await compareDirectories(committed, copy), ['extra.ts: unexpected file', 'manifest.ts: missing']);
});

test('normalize orders by type name and drops ts-rs headers and imports', () => {
  const raw = [
    '// This file was generated by [ts-rs](x). Do not edit.',
    'import type { B } from "./b";',
    '',
    'export type Z = number;',
    '',
    '/**',
    ' * doc',
    ' */',
    'export type A = { b: B };  ',
    '',
    '/**',
    ' * shape {x}',
    ' */',
    'export type S = {',
    '/**',
    ' * field {y}',
    ' */',
    'f: { a: number }, };',
    '',
  ].join('\r\n');
  assert.equal(
    normalize(raw),
    [
      '// Generated by scripts/gen-types.mjs from alef-core. Do not edit.',
      '/**',
      ' * doc',
      ' */',
      'export type A = { b: B };',
      '',
      '/**',
      ' * shape {x}',
      ' */',
      'export type S = {',
      '  /**',
      '   * field {y}',
      '   */',
      '  f: { a: number }, };',
      '',
      'export type Z = number;',
      '',
    ].join('\n'),
  );
  assert.throws(() => normalize('const x = 1;\n'), /export type/);
});
