// SPDX-License-Identifier: MIT OR Apache-2.0
// Generates packages/api/types/*.ts from the Rust DTOs of alef-core and alef-modules (ts-rs).
//
// Adding a DTO: derive `ts_rs::TS` and write `#[ts(export, export_to = "<group>.ts")]`, where
// <group> is one of GROUPS (core.ts: errors, ids, host; manifest.ts: alef.ktav; modules.ts: replies
// of the modules). A DTO must not use a type of another group: the files do not import each other. During
// `cargo test export_bindings` ts-rs writes one file per group; this script merges the
// declarations in a stable order into the committed files. A new group needs an entry in GROUPS.
//   npm run gen:types    regenerate packages/api/types
//   npm run check:types  regenerate into a scratch directory and fail on any difference (CI)
import { spawnSync } from 'node:child_process';
import { createRequire } from 'node:module';
import { copyFile, mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../', import.meta.url));
const committedDir = path.join(root, 'packages', 'api', 'types');
const workDir = path.join(root, 'backend', 'target', 'gen-types');
const BANNER = '// Generated by scripts/gen-types.mjs from the Rust DTOs. Do not edit.\n';
const GROUPS = ['core.ts', 'manifest.ts', 'modules.ts'];
const OUTPUT = [...GROUPS, 'index.ts'];
const INDEX = BANNER + GROUPS.map(name => `export * from './${name.replace(/\.ts$/, '.js')}';\n`).join('');

const declarationName = text => /^export type (\w+)/m.exec(text)?.[1] ?? '';

// ts-rs prints object members at column 0; indent them one level (braces in comments do not count).
function indent(declaration) {
  let depth = 0;
  return declaration
    .split('\n')
    .map(line => {
      const closing = line.startsWith('}');
      const text = depth > 0 && !closing ? `  ${line}` : line;
      if (!/^\s*(\/\*|\*|\/\/)/.test(line)) {
        depth += (line.match(/\{/g) ?? []).length - (line.match(/\}/g) ?? []).length;
      }
      return text;
    })
    .join('\n');
}

// Drops ts-rs headers and imports (all types of a group share one file), sorts by type name.
export function normalize(source) {
  const lines = source
    .replaceAll('\r\n', '\n')
    .split('\n')
    .filter(line => !/^\/\/ This file was generated by \[ts-rs\]/.test(line) && !/^import\s/.test(line))
    .map(line => line.replace(/[ \t]+$/, ''));
  const declarations = lines
    .join('\n')
    .split(/\n\s*\n/)
    .map(part => part.trim())
    .filter(Boolean)
    .map(indent);
  if (declarations.some(part => declarationName(part) === '')) {
    throw new Error('Unexpected ts-rs output: a block without `export type`.');
  }
  declarations.sort((a, b) => declarationName(a).localeCompare(declarationName(b), 'en'));
  return `${BANNER}${declarations.join('\n\n')}\n`;
}

function run(command, args, env = {}) {
  const result = spawnSync(command, args, { cwd: root, env: { ...process.env, ...env }, stdio: 'inherit' });
  if (result.error) throw result.error;
  return result.status;
}

function typecheck(directory) {
  const tsc = path.join(path.dirname(createRequire(import.meta.url).resolve('typescript/package.json')), 'bin', 'tsc');
  const files = OUTPUT.map(name => path.join(directory, name));
  const flags = ['--ignoreConfig', '--noEmit', '--strict', '--skipLibCheck', '--target', 'ES2022', '--module', 'ESNext', '--moduleResolution', 'bundler'];
  if (run(process.execPath, [tsc, ...flags, ...files]) !== 0) {
    throw new Error('The generated TypeScript does not typecheck.');
  }
}

// Runs the ts-rs export tests into `directory` and writes the merged files there.
export async function generateInto(directory) {
  await rm(directory, { recursive: true, force: true });
  await mkdir(directory, { recursive: true });
  const env = { TS_RS_EXPORT_DIR: directory, TS_RS_LARGE_INT: 'number' };
  const status = run('node', ['scripts/cargo.mjs', 'test', '--locked', '-p', 'alef-core', '-p', 'alef-modules', 'export_bindings'], env);
  if (status !== 0) throw new Error(`The ts-rs export tests failed (exit ${status}).`);
  const produced = (await readdir(directory)).filter(name => name.endsWith('.ts'));
  const unknown = produced.filter(name => !GROUPS.includes(name));
  if (unknown.length > 0) throw new Error(`Unknown export group(s) ${unknown.join(', ')}; add them to GROUPS.`);
  for (const name of GROUPS) {
    const file = path.join(directory, name);
    await writeFile(file, normalize(await readFile(file, 'utf8')));
  }
  await writeFile(path.join(directory, 'index.ts'), INDEX);
  typecheck(directory);
}

const read = file => readFile(file, 'utf8').catch(() => null);

// Differences between a generated and a reference directory; empty when identical.
export async function compareDirectories(generatedDir, referenceDir) {
  const present = (await readdir(referenceDir).catch(() => [])).filter(name => name.endsWith('.ts'));
  const differences = [];
  for (const name of [...new Set([...OUTPUT, ...present])].sort()) {
    const expected = await read(path.join(generatedDir, name));
    const found = await read(path.join(referenceDir, name));
    if (expected === found) continue;
    if (found === null) differences.push(`${name}: missing`);
    else if (expected === null) differences.push(`${name}: unexpected file`);
    else {
      const wanted = expected.split('\n');
      const actual = found.split('\n');
      const line = wanted.findIndex((text, index) => text !== actual[index]);
      differences.push(`${name}: differs at line ${(line < 0 ? wanted.length : line) + 1}`);
    }
  }
  return differences;
}

async function main(mode) {
  if (mode !== undefined && mode !== '--check') throw new Error(`Unknown option: ${mode}`);
  const directory = path.join(workDir, mode === '--check' ? 'check' : 'write');
  await generateInto(directory);
  if (mode === '--check') {
    const differences = await compareDirectories(directory, committedDir);
    if (differences.length > 0) {
      throw new Error(`Generated types are out of date (run npm run gen:types):\n  ${differences.join('\n  ')}`);
    }
    return;
  }
  await mkdir(committedDir, { recursive: true });
  for (const name of OUTPUT) await copyFile(path.join(directory, name), path.join(committedDir, name));
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main(process.argv[2]).catch(error => {
    console.error(error.message);
    process.exitCode = 1;
  });
}
